### ISSUE TITLE
Publishing files bigger than 64kb ? 

### ISSUE THREAD

**Issue by the-mind** [LiamBindle/MQTT-C#101]
Quick question, does this fix https://github.com/LiamBindle/MQTT-C/pull/83 allow you to publish files as large as 20mb to  200mb? If not, what can I change to support it ? 

At the moment, I seem unable to publish files as large as 1mb, please help.

**Comment by LiamBindle** [comment]
I believe the standard says 260 MB is the upper limit, but I haven't tried sending large messages as large as 1 MB. Could you describe what happens when you try? Does it seg fault? Or does it fail to transmit? I'm sure you've done this but make sure your send/recv buffers are large if you're sending payloads that big.

**Comment by pmfsoares** [comment]
Hi, not the OP, but I'm also having some problems sending bigger payloads, in my code I'm sending a JSON string that is roughly 2MB, and from what I've tested it doesn't crash/seg fault, it just simply doesn't transmits, I used wireshark to confirm if was sending them, but the packets don't even appear on the network. So my guess is that it isn't simply transmitting.
