### ISSUE TITLE
local persistence

### ISSUE THREAD

**Issue by Grabber** [LiamBindle/MQTT-C#139]
Is there any feature to provide local persistence in the case of energy shutdowns?

**Comment by LiamBindle** [comment]
Not really. If you hard-code your broker's address/creds/etc then the connection will always be reinitialized, but I can't think of anything beyond that. It would get tricky because the socket would somehow need to be persistent. If you could get a persistent socket, then in theory you could serialize and dump the `mqtt_client` struct and reload it
