### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by djarvis** [LiamBindle/MQTT-C#15]
Any plans to support websockets?

**Comment by LiamBindle** [comment]
Yeah, I think so. Currently I'm working on OpenSSL support (hopefully completed this weekend), but I think supporting websockets next would make sense. I'm going to change this thread to a feature request and update the title accordingly if that's okay.

I haven't worked with websocekts before though, so if I'm doing the implementation I'll need a bit of time to get caught up on websockets. Are there any websockets libraries that you can suggest? Maybe [LWS3](https://libwebsockets.org/)?

If someone else wants to take on this project (essentially implement `mqtt_pal_sendall` and `mqtt_pal_recvall` for websockets and give an example) let me know and I'll help get you started. Otherwise, I'll get started on this next week.

**Comment by LiamBindle** [comment]
I'm going to mark this as "wontfix" because I'm not going to have time to add this in the next little while.

If anyone would like to take this on (it's not a big job) please let me know and I'd be happy to help get you started.

Liam
