### ISSUE TITLE
simple_publisher tested on Ubuntu 16.04 and AIX 6.1

### ISSUE THREAD

**Issue by pointbre** [LiamBindle/MQTT-C#32]
* Ubuntu 16.04
  * gcc -Wextra -Wall -std=gnu99 -Iinclude -Wno-unused-parameter -Wno-unused-variable -Wno-duplicate-decl-specifier examples/simple_publisher.c src/mqtt.c src/mqtt_pal.c -lpthread -o bin/simple_publisher
  * terminal 1: mosquitto_sub -h test.mosquitto.org -t "/datetime"
  * terminal 2: ./bin/simple_publisher test.mosquitto.org 1883 "/datetime"

* AIX 6.1
  * cc -Iinclude examples/simple_publisher.c src/mqtt.c src/mqtt_pal.c -lpthread -o bin/simple_publisher
  * terminal 1: mosquitto_sub -h test.mosquitto.org -t "/datetime"
  * terminal 2: ./bin/simple_publisher test.mosquitto.org 1883 "/datetime"

I have struggled with compilation and test which is why I'm leaving this note here. I hope you can put this to  the example folder if you think this is helpful.

Thanks for your great work.
Lucas

**Comment by LiamBindle** [comment]
Hi,

Thanks for the feedback. Glad to hear things are working okay for you now. Feel free to let me know if you run into any problems.

Using the `simple_publisher` example with the mosquitto clients is a good sanity check, but I'm hesitant to add it to the examples directory because I want to keep the examples as simple as possible with minimal dependencies.

Glad to hear it's running on AIX okay&mdash; I always appreciate hearing where MQTT-C is being used 😄 

Thanks again for the feedback!

Liam
