### ISSUE TITLE
PINGRESP callback

### ISSUE THREAD

**Issue by Josh798** [LiamBindle/MQTT-C#39]
Hi Liam,

Does this library provide a way to notify my application of a PINGRESP message? I can't find it in the docs, and I didn't immediately see anything regarding this in the source. If this functionality was intentionally left out of the library, just let me know. If not, I'm willing to take a shot at implementing it.

In my system, I have multiple brokers that could disappear silently at any moment, and I'm looking for a clean way to detect if they're still alive. Let me know if you know of a better way to accomplish this.

Thanks,
Josh

**Comment by LiamBindle** [comment]
Hi Josh,

MQTT-C should actually already be doing what you're trying to accomplish. MQTT uses a "keep alive time", where if the connection has been quiet for `mqtt_client::keep_alive` seconds, a PING is sent to the broker, and the broker HAS to respond. If the broker weren't to respond to one of these keep-alive messages you would get a full on `MQTT_ERROR`.

Take a look at the [`keep_alive`](https://liambindle.ca/MQTT-C/structmqtt__client.html#aff533344a060e58277698039f547147a) time and set it to whatever you think is appropriate (don't make it too short though).

## Regarding passing PINGRESPs to the user's callback
This might be useful. MQTT uses pings when the elapsed time since your last message approaches the "keep alive time", so I guess the reason I didn't implement it initially it that you would receive these from "behind the scenes" things that are going on. Do you think it would be useful to forward PINGRESPs to the user's callback? I'm open to it if you think there are real use cases for this.

Liam

**Comment by LiamBindle** [comment]
Hi Josh, 

I'm going to close this issue. Feel free to reopen it if you'd like.

Liam
