### ISSUE TITLE
How do you know if an operation is successful

### ISSUE THREAD

**Issue by foufee** [LiamBindle/MQTT-C#44]
Since all the API's (subscribe, publish, connect) all return with MQTT_OK once the packet is in the queue, how can you find out if the associated SubACK, PubACK or ConnACK has been received?

**Comment by LiamBindle** [comment]
Right now there isn't really a way to do this explicitly in MQTT-C, but it should be relatively easy to accomplish what I think you're wanting to do. 

Before that though, I should mention that error states are taken seriously in MQTT-C, and `MQTT_OK` isn't always returned. If the client _ever encounters an error_, the function will return the appropriate error code. And these error codes are taken seriously in MQTT-C. If it doesn't do this, this is a bug in MQTT-C and I urge anyone to please report it. 

So, if you're API functions are returning `MQTT_OK` you should believe the operation was successful.

---

You also asked if it's possible to find out if the message has been received. This is tricky to do explicitly because operations like `mqtt_publish` only stage messages in the message queue, whereas `mqtt_sync` actually sends queued messages and receives incoming messages. 

If you do need to see if the network is active, you can use a combination of [`mqtt_client::number_of_timeouts`](https://liambindle.ca/MQTT-C/structmqtt__client.html#af5fed75fb3f83137d5c7635693cd7b6c) and [`mqtt_client::response timeout`](https://liambindle.ca/MQTT-C/structmqtt__client.html#a4ee652148f2b1b338f1527a85879e970). The response timeout is the number of seconds before an unacknowledged packet is said to have timed-out and the original packet retransmitted. Everytime this happens the number of timeouts counter will be incremented. 

Hope this answers your question. Let me know if you need clarifiaction on anything. 

--Liam

**Comment by foufee** [comment]
Hi,
  What I ended up doing was adding a "ack_callback" to the client object, and additionally passing a void* client_packet_identifier to each of the API's I was interested in (open, publish, subscribe and unsubscribe). The client_packet_identifier was also stored in the message queue, and then in _mqtt_read, as the ACK was received, the callback was triggered with an integer (1 == ack, 0 == timeout or failed) and the client_packet_identifier. This was the application was able to keep track of what packets had been sent and ack'ed (without this, when used with Amazon CoreIoT it kicks you out if you queue too many packets before the acks are received.

  I will check to see if I can post a PR of my changes, if not...the idea (if you want it) is pretty simple.

**Comment by LiamBindle** [comment]
Yeah, I see what you did. I haven't heard any other requests for ths feature to be added to MQTT-C, so I think I'd hold off until I hear more similar requests.

Anyways, glad you figured it out! I'm closing this issue but feel free to reopen at any time.
