### ISSUE TITLE
MQTT_ERROR_SEND_BUFFER_IS_FULL error periodically

### ISSUE THREAD

**Issue by daanpape** [LiamBindle/MQTT-C#65]
Hello,

I'm using MQTT-C in a project and I'm very happy with it. I based my multithreaded implementation on the `reconnect_subscriber` example and it works very good except for one thing. I'm publishing 1 message of 155 bytes every 2.5 seconds.

I originally had a send buffer size of 102400 bytes and I saw repeated error states containing the MQTT_ERROR_SEND_BUFFER_IS_FULL error. To test if this was a spurious error I have now made the send buffer smaller to 1550 bytes. I now get the error every 6 messages.

I have multiple threads in the program:

- A sync thread which calls `mqtt_sync` and `mqtt_mq_clean` every 10ms:

```C
while(true) {
  mqtt_sync(&mqtt_client);
  mqtt_mq_clean(&(mqtt_client.mq));
  helper_sleep_ms(10);
}
```
 - A transmit thread which reads a FiFo queue and calls the `mqtt_publish` routine:

```C
if(message.data_size == 0) {
  mqtt_publish(&_dbtalk_network_grouptalk_client, message.topic, "", 0, MQTT_PUBLISH_QOS_0);
} else {
  mqtt_publish(&_dbtalk_network_grouptalk_client, message.topic, message.data, message.data_size, MQTT_PUBLISH_QOS_0);
}
  mqtt_sync(&_dbtalk_network_grouptalk_client);
  free(message.topic);
  free(message.data);
```

Following is my `reconnect_handler` function:

```C
void _reconnect_handler(struct mqtt_client* client, void **args)
{
    while(true) {
        close(client->socketfd);
        client->socketfd = -1;

        if(client->error != MQTT_ERROR_INITIAL_RECONNECT) {
            log_error("MQTT", "Connection was in error state: %s\n", mqtt_error_str(client->error));
        }

        int fd = _open_client_socket(MQTT_ADDRESS, MQTT_PORT);
        if(fd == -1) {
            helper_sleep_ms(500);
            continue;
        }

        mqtt_reinit(client, fd, send_buffer, SENDBUF_SIZE, receive_buffer, RECVBUF_SIZE);

        enum MQTTErrors retvalue = mqtt_connect(client, "mqtt-client", NULL, NULL, 0, NULL, NULL, 0, 400);
        if(retvalue != MQTT_OK) {
            log_error("MQTT", "Could not connect to the broker (%d): %s\n", retvalue, mqtt_error_str(retvalue));
            helper_sleep_ms(500);
            continue;
        }
        
        for(int i = 0; i < MQTT_TOPIC_COUNT; ++i) {
            const char *topic = _get_topic(i);
            
            retvalue = mqtt_subscribe(client, topic, 0);            
            if(retvalue != MQTT_OK) {
                log_error("MQTT", "Could not subscribe to topic '%s' (%d): %s\n", topic, retvalue, mqtt_error_str(retvalue));
                continue;
            }
        }

        log_info("MQTT", "Connected to the broker and subscribed to MQTT topics\n");
        return;
    }
}
```

Could you please give me some pointer on what is going on?

**Comment by LiamBindle** [comment]
Hi @daanpape, thanks for writing. 

That is strange, especially since your messages are QOS 0. Since they're QoS 0, all your publish messages should go to the `MQTT_QUEUED_COMPLETE` state as soon as `__mqtt_send` (called in `mqtt_sync`) is called (that happens [here](https://github.com/LiamBindle/MQTT-C/blob/24b1de6f0e632d0f3ccbb27e5ef1ce355abe54cd/src/mqtt.c#L574)). 

Do you think it's possible there's a message at the head of your message queue that remains in some unackknowledged state (e.g. your connection request)? When `mqtt_mq_clean` is called, it can only free-up space from the start of the buffer to the first message that *is not* `MQTT_QUEUED_COMPLETE`. If, for example, you never receive the CONNACK packet from the broker, the CONNECT message at the head of your queue would prevent the entire message queue from ever being cleaned ([here](https://github.com/LiamBindle/MQTT-C/blob/24b1de6f0e632d0f3ccbb27e5ef1ce355abe54cd/src/mqtt.c#L697) is where the received CONNACK puts your initial CONNECT message into the completed state).

To troubleshoot your issue, you could try inspecting your message queue ([here](https://liambindle.ca/MQTT-C/group__details.html) is the documentation for working the with message queue). You could essentially loop through each message in the queue (you can get the messages with `mqtt_mq_get`) and inspect its state (e.g. `MQTT_QUEUED_AWAITING`) and control type (e.g. `MQTT_CONTROL_PUBLISH`).

Side question: are you using the default Unix PAL? Are you working on any unusual architectures or platforms?

**Comment by daanpape** [comment]
Hello @LiamBindle,

Thank you for the fast reply. I'm first going to answer your other questions:

1. Yes I'm using an unmodified PAL file.
2. I'm running the software on OpenWRT on a MIPS processor
3. I'm using a broker i wrote myself but which is tested with multiple MQTT clients

To answer your first question: I learned that everything is possible :), ok now to be more serious. I highly doubt that there would be a pending CONACK. I have monitored traffic between my broker and the mqttfx client application with the following result:

![image](https://user-images.githubusercontent.com/6665380/70076613-70b56000-15ff-11ea-97cb-7d4b5fbde1d8.png)

It seems to me that the broker responds correctly with a CONACK. I'm now going to look to the docs and try to inspect the transmit queue. I will update with more info soon.

Kind regards,
Daan

**Comment by daanpape** [comment]
Hello @LiamBindle,

I managed to see the problem by inspecting the message queue: 

```C
MQTT_PAL_MUTEX_LOCK(&client.mutex);

        for(size_t i = 0; i < mqtt_mq_length(&(client.mq)); ++i) {
            struct mqtt_queued_message *msg = mqtt_mq_get(&(client.mq), i);

            log_debug("MQTT", "Message %d has state %s and control type %s\n", i, _mqtt_state_to_str(msg->state), _mqtt_control_type_to_str(msg->control_type)); 
        }

        MQTT_PAL_MUTEX_UNLOCK(&client.mutex);
```

And I now get the output:

```
[2019-12-03 19:24:14][DEBUG][MQTT] Message 0 has state MQTT_QUEUED_AWAITING_ACK and control type MQTT_CONTROL_SUBSCRIBE
[2019-12-03 19:24:14][DEBUG][MQTT] Message 1 has state MQTT_QUEUED_AWAITING_ACK and control type MQTT_CONTROL_SUBSCRIBE
[2019-12-03 19:24:14][DEBUG][MQTT] Message 2 has state MQTT_QUEUED_AWAITING_ACK and control type MQTT_CONTROL_SUBSCRIBE
[2019-12-03 19:24:14][DEBUG][MQTT] Message 3 has state MQTT_QUEUED_COMPLETE and control type MQTT_CONTROL_PUBLISH

```

**Comment by daanpape** [comment]
I have now updated my broker implementation and this completely fixed the problem. Thanks again @LiamBindle

**Comment by LiamBindle** [comment]
@daanpape Oh great, I'm glad you got your issue solved! :smile: Let me know if you run into any more problems.
