### ISSUE TITLE
Question about possible bug in send logic

### ISSUE THREAD

**Issue by andrewchambers** [LiamBindle/MQTT-C#66]
So I was reviewing the code and see something that confuses me:

It a message is partially sent:
```
   if(client->send_offset < msg->size) {
              /* partial sent. Await additional calls */
              break;
            } else {
```
But then a resent timeout occurs:
```
   /* check for timeout */
            if (MQTT_PAL_TIME() > msg->time_sent + client->response_timeout) {
                resend = 1;
                client->number_of_timeouts += 1;
                client->send_offset = 0;
            }
```

It seems to me you will be sending broken half packets since you reset send_offset halfway through a send of a packet.

It seems this bug doesn't happen in practice because there is a bug in the send calls for unix:

```

ssize_t mqtt_pal_sendall(mqtt_pal_socket_handle fd, const void* buf, size_t len, int flags) {
    size_t sent = 0;
    while(sent < len) {
        ssize_t tmp = send(fd, buf + sent, len - sent, flags);
        if (tmp < 1) {
            return MQTT_ERROR_SOCKET_ERROR;
        }
        sent += (size_t) tmp;
    }
    return sent;
}
```

You don't seem to be handling WOULD_BLOCK or EAGAIN for sending on a non blocking socket, this seems like a bug to me also, as the code seems to be attempting to handle blocking writes.

do these seem like bugs to you? or have I misunderstood?

**Comment by LiamBindle** [comment]
Hi Andrew, thanks for opening the issue. You bring up a good point&mdash;I don't think partially sent messages are continued properly by subsequent `mqtt_sync()` calls.

### Partially sent messages
That being said, I don't think I'd consider this a bug, just because MQTT-C doesn't claim to support such a feature. The `mqtt_pal_sendall()` function is supposed to send *everything* in the send buffer, otherwise return an error. 

That being said, I think this would be a good feature! And I'd be more than happy to merge a PR with this feature if you're interested in implementing it!


### The PAL
Regarding the PAL, the PAL is intentionally simple. The PAL in mqtt_pal.c is meant to be used as a starting point for porting/improving to make your own PAL, so it's meant to be as simple and easy to understand as possible. 

A conditional that checks EWOULDBLOCK/EAGAIN to continue the while loop rather than return a socket error would be a good update though, and I'd be happy to merge a PR.

Cheers,

Liam

**Comment by andrewchambers** [comment]
Thanks for the reply, I think I had assumed the code was meant to work with non blocking sockets, but I can see that was just an assumption on my part.

I imagine not too much is needed to implement such a feature, but I don't have a need as in the end I used redis pubsub instead of mqtt.

thanks again for the answer though. This is a great project.

**Comment by LiamBindle** [comment]
Fair enough. Thanks for bringing this to my attention!

Cheers,

Liam
