### ISSUE TITLE
Need help compile in Windows 10

### ISSUE THREAD

**Issue by kusumy** [LiamBindle/MQTT-C#69]
I clone this repo on the windows 10 machine.
Then i tried to build simple_publisher example using Visual Studio Code (using gcc as compiler), but there are an error messagea:

fatal error: mqtt.h: No such file or directory 

- error: unknown type name 'mqtt_pal_socket_handle'
 ssize_t mqtt_pal_sendall(mqtt_pal_socket_handle fd, const void* buf, size_t len, int flags);

- error: unknown type name 'uint32_t'
     uint32_t remaining_length;

and others ....

Need help, please ...

**Comment by LiamBindle** [comment]
Hi @kusumy. The problem is that the `include/` subdirectory of MQTT-C is included in the list of include directories that your compiler is using. I'm not familiar with gcc+VSCode, but the gcc flag for include directories is `-I`. I'd recommend looking up how to add include directories to your VSCode project.
