### ISSUE TITLE
Get data from subscribed topic

### ISSUE THREAD

**Issue by moravas** [LiamBindle/MQTT-C#70]
Hi Liam,

I am new to MQTT but in my project I have to use MQTT connection.
I have checked the examples, but I haven't see the point where I can read back the data belonging to topic I have subscribed to.
Can you extend one example, or just point to the right API here?

Thank you

**Comment by LiamBindle** [comment]
Hi @moravas. Could you expand on what you mean? What information about the topics you've subscribed to do you need? Do you mean the bits of the SUBACK packet?

**Comment by moravas** [comment]
@LiamBindle E.g.: in the simple_subscriber example, the mqtt client subscribe to the default topic: "datetime". 
As I understand MQTT, in this case, client gets update about topic change, if anybody publish same topic towards to the broker.

What I miss in these examples: how can read out the received topic change? How can I process that the "datetime" topic has changed?

**Comment by LiamBindle** [comment]
@moravas That's done by a callback. The simple_subscriber callback is called `publish_callback()` and is here:
https://github.com/LiamBindle/MQTT-C/blob/399361fb011577bf7c0444a08982a18a739f91fd/examples/simple_subscriber.c#L122-L132

For your application you're going to have to write your own callback function. You pass a pointer to your callback to `mqtt_init()`.

Since the simple_subscriber example only subscribes to one topic, this callback doesn't implement any logic to determine which the topic of the incoming message (it just assumes it's from "datetime"). The `struct mqtt_response_publish` object contains all the necessary informatino related to the incoming message though. You can find it's documentation [here](https://liambindle.ca/MQTT-C/structmqtt__response__publish.html).

Does that answer your question?

**Comment by moravas** [comment]
@LiamBindle This is exactly what I have looked for. The name was a bit confusing for me. Thank you.

**Comment by LiamBindle** [comment]
Great! No problem
