### ISSUE TITLE
What is the best way to publish data when receiving data through the callback?

### ISSUE THREAD

**Issue by cl-nkf** [LiamBindle/MQTT-C#77]
Hello, and thank you for you time for reading this. 

Firstly a bit of context on what my goal is.

When I receive data through the publish_response_callback  I want to publish data on a topic.

For example I modified the code in the reconnect_subscriber example and added a publish.
```C
void publish_callback(void** unused, struct mqtt_response_publish *published) 
{
    /* note that published->topic_name is NOT null-terminated (here we'll change it to a c-string) */
    char* topic_name = (char*) malloc(published->topic_name_size + 1);
    memcpy(topic_name, published->topic_name, published->topic_name_size);
    topic_name[published->topic_name_size] = '\0';
    printf("Received publish('%s'): %s\n", topic_name, (const char*) published->application_message);
    mqtt_publish(&client, "test", "test", strlen("test") + 1, MQTT_PUBLISH_QOS_0);
    free(topic_name);
}
```

However when doing this the sample is stuck in the mqtt_publish function before Mutexing the client.

I quick-fixed this by adding a mutex unlock in the mqtt.c around the line 734
```C
ssize_t __mqtt_recv(struct mqtt_client *client) 
{
... 
case MQTT_CONTROL_PUBLISH:
  MQTT_PAL_MUTEX_UNLOCK(&client->mutex);
  /* call publish callback */
  client->publish_response_callback(&client->publish_response_callback_state, &response.decoded.publish);
}
```

So is this a bug, and my fix is the good way of doing this? Or is it an expected behavior and I shall make a thread in order to publish data in the callback?

**Comment by LiamBindle** [comment]
@cl-nkf Thanks for writing.

I think the best way would be to mark (e.g. with a global flag or in `mqtt_client::publish_response_callback_state`) that you received an ingress message and then have a thread/section of your program dispatching your publishes whenever it sees that mark. The contents of `publish_callback` should be kept pretty light because it is inside the mutex, and it's called in the internals of MQTT-C. I think it should be thought of as similar to interrupt callback.

I think your quick-fix might cause some infrequent problems--I'm thinking if there's a lot of ingress traffic, or if you're using QOS > 0 because in these cases your client's message queue will have multiple messages (so multiple loops through the while loop in `__mqtt_recv`). Unlocking the mutex in your callback does mean that the loop in `__mqtt_recv` will continue after your callback in the unlocked state (before it's unlocked again [here](https://github.com/LiamBindle/MQTT-C/blob/79c1b887856332fc12278e52c29532e9ebad2a8a/src/mqtt.c#L631)). Because of this, I think you should avoid calling `mqtt_publish` inside your callback.

In case you or someone else wants to add this functionality, I think you could do it by having ingress and egress mutexes (rather than the one mutex as it is right now). Anyways, that's just my 2c.

**Comment by cl-nkf** [comment]
Thank you for your quick answer. I'll rethink the way my API works then.
