### ISSUE TITLE
feedback about published message

### ISSUE THREAD

**Issue by ravdeepboparai** [LiamBindle/MQTT-C#82]
Hello All,
I was wondering how i can get to know that the message published is being acknowledged?
Can you please point to any documentation about it?

**Comment by LiamBindle** [comment]
Hi @ravdeepboparai, I assume you're talking about the broker's acknowledgement right? Internally, MQTT-C retransmits a message if an ACK is expected and the elapsed time since the message was sent is greater than [`mqtt_client::response_timeout`](https://liambindle.ca/MQTT-C/structmqtt__client.html#a4ee652148f2b1b338f1527a85879e970). If the elapsed time is greater than the response timeout, then the message is retransmitted and [`mqtt_client::number_of_timeouts`](https://liambindle.ca/MQTT-C/structmqtt__client.html#af5fed75fb3f83137d5c7635693cd7b6c) is incremented. This happens [here fyi](https://github.com/LiamBindle/MQTT-C/blob/79c1b887856332fc12278e52c29532e9ebad2a8a/src/mqtt.c#L497-L501).

**Comment by LiamBindle** [comment]
@ravdeepboparai I'm going to close this issue. Please feel free to reopen if you have any more questions.
