### ISSUE TITLE
Unaligned TX buffer leads to Segmentation/Hard Fault

### ISSUE THREAD

**Issue by vpetrigo** [LiamBindle/MQTT-C#91]
Hello,

As the implementation reflects MQTT TX buffer to the [internal memory queue][mq] that leads to Segmentation/Memory/Hard Faults on some platform. It definitely leads to Hard Fault on ARMv7-M architectures and most likely for other ARM architectures (ARMv7E-M, ARMv6, ARMv5, etc.) upon a write access operation. On the x86/x86-64 platform it is not so critical as it supports unaligned pointer read/write access, but it definitely would drop performance as unaligned access has its cost.

So, I see the following options:
- document that TX buffer should be aligned to word boundary
- silently check alignment and operate on aligned part of provided buffer

Would you tell if that makes sense for you?

[mq]: https://github.com/LiamBindle/MQTT-C/blob/12492a703b7d3bbc8460db9ec61116c00709d612/src/mqtt.c#L108

**Comment by ericli1018** [comment]
@vpetrigo  I encountered that problem, is there a way to solve it?

**Comment by ericli1018** [comment]
@vpetrigo  Finally,  I solved by add "__attribute__((packed))" for every struct and enum in mqtt.h file.

**Comment by vpetrigo** [comment]
I solved it that way:
• `main.c`:
```c
static unsigned char mqtt_tx_buffer[MAX_TX_BUFFER_SIZE] __attribute__((aligned(4)));
static unsigned char mqtt_rx_buffer[MAX_RX_BUFFER_SIZE];

// ...
int main(void) {
    // ...
    mqtt_init(p_client, p_client->socketfd, mqtt_tx_buffer, sizeof mqtt_tx_buffer, mqtt_rx_buffer,
              sizeof mqtt_rx_buffer, message_callback);
   // ...
}
```

**Comment by sainsaar** [comment]
I've stumbled onto the same problem on ARM and used a very similar solution:
```c
static uint8_t mqtt_tx_buffer[8192] __attribute__((aligned)); 
```
This ensures maximum alignment. The requirement is for the TX buffer to be at least as aligned as `struct mqtt_queued_message`. It seems that that should be said in the documentation.

**Comment by LiamBindle** [comment]
Hi everyone, thanks for the discussion. I'm busy with work right now so I might be slow to respond. Thanks @ericli1018 @vpetrigo @sainsaar for chiming in. 

Would it be best to add a note for this in the documentation? I'll defer to what you guys think is best.

**Comment by vpetrigo** [comment]
Hello @LiamBindle,
I'm guessing that adding an attention note for the `mqtt_init` would be enough. I have prepared a PR and will be glad if you review that when you have a chance.

**Comment by brianrho** [comment]
From what I can tell, the message headers approach from the end of the TX buffer, whereas the actual message content approach from the start of the buffer. Whenever they meet, there is no more space for new messages.

Alignment matters usually for multi-byte access of random space (so we can ignore the arbitrary message content). Since the message headers are individual structs occupying the TX buffer, the buffer should be at least as aligned as `mqtt_queued_message`, like someone said above. 

Based on the contents of the struct, the natural alignment of `mqtt_queued_message` is likely 4 bytes on ARMv7 at least, which makes it fine to use `__attribute__((aligned(4)))` on the TX buffer. However, this attribute only ensures the buffer **starts** on a 4-byte boundary -- it does nothing about the end of the buffer, as far as I can tell.

This means one could potentially allocate a buffer of 513 bytes, and once the library does this decrement:
https://github.com/LiamBindle/MQTT-C/blob/be12c343ac5b7125d5e15cb9ab2d743de7f4fab4/src/mqtt.c#L1619-L1620

...it will land on an unaligned address, triggering said hard fault. So it looks like there should be an extra comment saying that the buffer sizes should be a multiple of 4 bytes. 

(The current 4-byte alignment is probably inappropriate for 64-bit systems, but if no issues have been reported so far, the relevant 64-bit systems probably offer complete support for unaligned access and don't care terribly.)
